#!/usr/bin/env bash
# This script installs nginx and modifies the default html file.

sudo apt-get update
sudo apt-get install -y  nginx=1.4.6-1ubuntu3.13
echo "Hello World!" > /var/www/html/index.html
service nginx start

